"""baseline: patients studies series instances

Revision ID: 20809e26d134
Revises: 
Create Date: 2026-05-12 10:23:07.937088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20809e26d134'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_patient_id'), 'patients', ['patient_id'], unique=True)
    op.create_table('studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_instance_uid', sa.String(length=255), nullable=False),
    sa.Column('patient_id', sa.String(length=255), nullable=False),
    sa.Column('modality', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studies_id'), 'studies', ['id'], unique=False)
    op.create_index(op.f('ix_studies_study_instance_uid'), 'studies', ['study_instance_uid'], unique=True)
    op.create_table('instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sop_instance_uid', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('study_instance_uid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['study_instance_uid'], ['studies.study_instance_uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instances_id'), 'instances', ['id'], unique=False)
    op.create_index(op.f('ix_instances_sop_instance_uid'), 'instances', ['sop_instance_uid'], unique=True)
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_instance_uid', sa.String(length=255), nullable=True),
    sa.Column('study_instance_uid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['study_instance_uid'], ['studies.study_instance_uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_id'), 'series', ['id'], unique=False)
    op.create_index(op.f('ix_series_series_instance_uid'), 'series', ['series_instance_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_series_series_instance_uid'), table_name='series')
    op.drop_index(op.f('ix_series_id'), table_name='series')
    op.drop_table('series')
    op.drop_index(op.f('ix_instances_sop_instance_uid'), table_name='instances')
    op.drop_index(op.f('ix_instances_id'), table_name='instances')
    op.drop_table('instances')
    op.drop_index(op.f('ix_studies_study_instance_uid'), table_name='studies')
    op.drop_index(op.f('ix_studies_id'), table_name='studies')
    op.drop_table('studies')
    op.drop_index(op.f('ix_patients_patient_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
